name: PR Check

on:
  pull_request:
    branches: [ main, master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
          
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
            
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Type check
        run: pnpm run type-check
        
      - name: Build package
        run: pnpm run build
        
      - name: Build documentation
        run: pnpm run docs:build
        
      - name: Check for build artifacts
        run: |
          if [ ! -d "dist" ]; then
            echo "❌ Build artifacts not found"
            exit 1
          fi
          echo "✅ Build artifacts found"
          
      - name: Check for docs build
        run: |
          if [ ! -d "docs/.vitepress/dist" ]; then
            echo "❌ Documentation build not found"
            exit 1
          fi
          echo "✅ Documentation build found" 